/*
* This file was generated by a tool.
* Rerun sql - ts to regenerate this file.
*/
export interface MemoModel {
    'id': number;
    'message'?: string | null;
    'createdAt'?: Date | null;
    'updatedAt'?: Date | null;
}
export interface TestTableModel {
    'id': number;
    'name'?: string | null;
    'description'?: string | null;
}